seedling/core/urls.py
from django.urls import path

from .views import HomeView

# These URLs are loaded by seedling/urls.py.
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

seedling/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
#import multitenancy.urls

from .core import urls as core_urls


urlpatterns = [
    # User management
    path("users/", include("seedling.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # This setup assumes that you're making an access.caltech app, which needs the app name as a prefix for all URLs.
    # If that's not true, you can change this to whatever base path you want, including ''.
    path('', include(core_urls, namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Add the root site interface
#urlpatterns += multitenancy.urls.urlpatterns

if settings.DEVELOPMENT:
    # We don't provide this in test/production because we don't want it there
    urlpatterns.append(path(settings.ADMIN_URL, include(admin.site.urls[:2], namespace=admin.site.name)))
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")}),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")}),
        path("500/", default_views.server_error),
    ]

if settings.ENABLE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

seedling/users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.urls import path

from seedling.users.views import (
    UserListView,
    UserRedirectView,
    UserUpdateView,
    UserDetailView,
)

app_name = "users"
urlpatterns = [
    path("", view=UserListView.as_view(), name="users--list"),
    path("~redirect/", view=UserRedirectView.as_view(), name="user--redirect"),
    path("~update/", view=UserUpdateView.as_view(), name="user--update"),
    path("<str:username>/", view=UserDetailView.as_view(), name="user--detail"),
]

seedling/core/models.py
from django.db import models

# Create your models here.

seedling/users/models.py
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    full_name = CharField(_("Full Name"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

seedling/core/forms.py
####################################
# Define your core app's forms here.
####################################

seedling/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

seedling/core/views.py
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

from wildewidgets import (
    BasicMenu,
    MenuMixin,
)


class MainMenu(BasicMenu):
    items = [('Home', 'core:home')]


class HomeView(MenuMixin, TemplateView):
    template_name = "core/home.html"
    menu_class = MainMenu
    menu_item = "Home"

    def get_context_data(self, **kwargs):
        kwargs['mydata'] = 'Here is my data.'
        return super().get_context_data(**kwargs)

seedling/users/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(
    LoginRequiredMixin,
    DetailView
):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


class UserListView(
    LoginRequiredMixin,
    ListView
):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


class UserUpdateView(
    LoginRequiredMixin,
    UpdateView
):

    model = User
    fields = ["full_name"]

    def get_success_url(self):
        return reverse("users:user--detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


class UserRedirectView(
    LoginRequiredMixin,
    RedirectView
):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:user--detail", kwargs={"username": self.request.user.username})

seedling/core/templates/core/_breadcrumb.html
<li class="breadcrumb-item active" aria-current="page">
  {% if url %}<a href="{{ url }}">{% endif %}
  {{ title }}
  {% if url %}</a>{% endif %}
</li>

seedling/core/templates/core/_main_menu.html
<ul class="nav page__navigation">
  <li class="nav-item page__navigation__item {% if active == 'Home' %} active{% endif %}">
    <a class="nav-link" href="{% url 'core:home' %}">Home</a>
  </li>
</ul>

seedling/core/templates/core/home.html
{% extends 'core/intermediate.html' %}
{% load i18n static %}

{% block title %}{% trans 'Seedling' %}{% endblock %}

{% block content %}
  <h2>Hello from Seedling</h2>

  <p class="introduction">
    {% if user.is_authenticated %}
      You are logged in as {{user}}.
    {% else %}
      You are not logged in.
    {% endif %}
  </p>

  <p>
    {{ mydata }}
  </p>
{% endblock %}

seedling/core/templates/core/intermediate.html
{% extends 'theme/base.html' %}
{% load i18n static seedling sass_tags %}

{% block title %}{% trans 'Seedling' %}{% endblock %}
{% block page_title %}{% trans 'Seedling' %}{% endblock %}
{% block application_name %}{% trans 'Seedling' %}{% endblock %}

{% block extra_css %}
  <link rel="stylesheet" href="{% sass_src 'core/css/core.scss' %}">
{% endblock %}

{% block breadcrumbs %}
  <nav aria-label="breadcrumb" class="ribbon__content__login__breadcrumbs">
    <ol class="breadcrumb ribbon__content__login__breadcrumbs__breadcrumb">
    {% block breadcrumb-items %}
      {% breadcrumb 'Seedling' 'core:home' %}
    {% endblock %}
    </ol>
  </nav>
{% endblock %}

{% block navigation %}
  {% main_menu 'Home' %}
{% endblock %}

seedling/theme/templates/theme/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

seedling/theme/templates/theme/base.html
{% load static i18n sass_tags %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:'en' }}" class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {# As of June 2018, this is the most up-to-date "responsive design" viewport tag. #}
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" href="{% static 'theme/img/apple-touch-icon.png' %}">
  <link rel="apple-touch-icon" sizes="120x120" href="{% static 'theme/img/apple-touch-icon-120x120-precomposed.png' %}">
  <link rel="apple-touch-icon" sizes="152x152" href="{% static 'theme/img/apple-touch-icon-152x152-precomposed.png' %}">
  <link rel="apple-touch-icon" sizes="167x167" href="{% static 'theme/img/apple-touch-icon-167x167-precomposed.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'theme/img/apple-touch-icon-180x180-precomposed.png' %}">
  <title>
    {% block title %}{% endblock %}
  </title>
  <link rel="shortcut icon" href="{% static 'theme/favicon.ico' %}" />

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <link rel="stylesheet" href="{% sass_src 'theme/css/theme.scss' %}">

  {% block extra_css %}
    {# Override this in templates to add extra stylesheets. #}
  {% endblock %}

  {# Datatables need this loaded first #}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  {% block extra_header_js %}
    {# Override this in subtemplates to add additional javascript to the page. Remember to use defer. #}
  {% endblock %}
</head>

<body>
  <div class="sr-only sr-only-focusable">
    <a href="#main-content-anchor">{% trans 'Skip to main content' %}</a>
  </div>
  <div class="page responsive-container mt-5">
    <div class="mb-5">
      <nav class="navbar navbar-expand-md navbar-light bg-light p-3">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'core:home' %}">Seedling</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:user--detail' request.user.username  %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="page__header d-flex flex-column flex-md-row align-items-md-center pb-4">
      {% block logo_title %}
        {# Sites which should not have Caltech branding can override the logo_title block to replace this. #}
        <img class="page__header__logo" src="{% static 'theme/img/logo.png' %}" alt="Seedling">
        <h1 class="title header__title page__header__title">
          {% block application_name %}Seedling{% endblock %}
        </h1>
      {% endblock %}
    </div>

    {% block main_menu %} {% endblock %}

    <a id="main-content-anchor"></a>
    <section class="page__content {% block content_classes %}{% endblock %}">
      {% block messages %}
        <div class="messages d-flex-column pl-0 mt-2">
          {% for message in messages %}
            <div class="messages__item alert alert-dismissible{% if message.tags %} alert-{{ message.tags }}{% else %}alert-info{% endif %}">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        </div>
      {% endblock %}
      {% block content %}
        {# This block is where templates place their primary page content. #}
      {% endblock %}
    </section>
  </div>

  <footer class="footer {% block footer_classes %}{% endblock %}">
    <div class="footer__content responsive-container d-flex flex-row align-items-stretch justify-content-between">
      {# FIXME: read contact information from settings. #}
      <div class="footer__content__contact pr-4">
          <div><a href="https://www.caltech.edu">California Institute of Technology</a></div>
          <div>1200 East California Boulevard, Pasadena, CA 91125</div>
          <div>© {% now 'Y' %} California Institute of Technology</div>
      </div>
      {# FIXME: read these links from settings. #}
      <ul class="footer__content__links d-flex align-self-center">
        <li><a href="https://www.imss.caltech.edu">IMSS Home</a></li>
        <li><a href="https://hr.caltech.edu/documents/44-citpolicy_einfo.pdf">Terms of Use</a></li>
      </ul>
    </div>
  </footer>

  <!-- jQuery first, then Popper.js, then Bootstrap JS, as specified by the Bootstrap docs. -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="{% static 'theme/js/theme.js' %}"></script>
  {% block extra_footer_js %}
  {% endblock %}
</body>
</html>

seedling/users/templates/users/user_detail.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:user--update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

seedling/users/templates/users/user_form.html
{% extends "theme/base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:user--update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

seedling/users/templates/users/user_list.html
{% extends "theme/base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:user--detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}